### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by fgadaleta** [expenses/face_recognition#7]
Running `cargo run --example draw`

Returns

```
18 |     image.put_pixel(point.x as u32, point.y as u32, colour);
   |                           ^ method, not a field
```

**Comment by expenses** [comment]
Is it broken or not?

**Comment by fgadaleta** [comment]
I recompiled with features and it compiles (with tons of warnings though).
I closed the issue because that error was no longer there. I'll run my tests locally and reopen the issue if needed.
